---
- hosts: all
  tasks:
  - name: output 1
    debug:
      msg: "Hello world!!!"

  - name: Load variables from test.yml
    include_vars: ../test.yml
  
  - name: output 1
    debug:
      msg: "Value of var1 is: {{var1}}"

  - name: output 2
    debug:
      var: WAWIADM_PW

  - name: output 3
    debug:
      var: USER1
      
  - name: output 4
    debug:      
      msg: 
        - "'{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}'"
        - "'{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}'"

  - name: output 4
    debug:      
      msg: 
        -  "{{ ansible_user }}"
        -  "{{ ansible_password }}"      
    
