---
- hosts: all
  collections:
    - awx.awx
    
  tasks:
  
  - name: Export all assets
    awx.awx.tower_export:
      all: True
      #validate_certs: no
    vars:  
      #verify_ssl: False
      tower_username: admin
      tower_password: test123
      ansible_python_interpreter: /usr/bin/python3
    register: exp_result
  
  - name: Output exp_result
    debug:
      var: exp_result 


  - meta: end_play   


  - name: Users AWX raises ERROR need https but awx runs on http
    tower_user:
      username: test
      first_name: FirstName
      last_name: LastName
      email: email@example.com
      password: changeme
    vars:  
      verify_ssl: False
      tower_username: admin
      tower_password: test123


 
  
  
  - name: output 1
    debug:
      msg: "Hello world!!!"

  - name: Load variables from test.yml
    include_vars: ../test.yml
  
  - name: output 1
    debug:
      msg: "Value of var1 is: {{var1}}"

  - name: output 2
    debug:
      var: wawiadm_pw

  - name: output 3
    debug:
      var: USER1
      
  - name: output 4
    debug:      
      msg: 
        - "'{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}'"
        - "'{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}'"

  - name: output 5
    debug:      
      msg: 
        - "'{{ lookup('env', 'ENV_WAWIADM') }}'"
        - "'{{ lookup('env', 'ENV_STDADM') }}'"
        - "'{{ lookup('env', 'ENV_STRADM') }}'"    
        - "'{{ lookup('env', 'ENV_SYS_PW') }}'"
