---
- hosts: all
  collections:
    - awx.awx
    
  tasks:
  - name: Export all assets
    awx.awx.tower_export:
      all: True
      validate_certs: no
    register: exp_result
  
  - name: Output exp_result
    debug:
      var: exp_result
  
  
  
  
  
  - meta: end_play
  
  - name: output 1
    debug:
      msg: "Hello world!!!"

  - name: Load variables from test.yml
    include_vars: ../test.yml
  
  - name: output 1
    debug:
      msg: "Value of var1 is: {{var1}}"

  - name: output 2
    debug:
      var: wawiadm_pw

  - name: output 3
    debug:
      var: USER1
      
  - name: output 4
    debug:      
      msg: 
        - "'{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}'"
        - "'{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}'"

  - name: output 5
    debug:      
      msg: 
        - "'{{ lookup('env', 'ENV_WAWIADM') }}'"
        - "'{{ lookup('env', 'ENV_STDADM') }}'"
        - "'{{ lookup('env', 'ENV_STRADM') }}'"    
        - "'{{ lookup('env', 'ENV_SYS_PW') }}'"
